version: "3"

services:
  db:
    restart: always
    image: postgres:12.2-alpine
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./redis:/data

networks:
  internal_network:
    internal: true
  external_network:
